User interactivity
jcmugabi/GithubUsersApp pull request #2
Opened 2024-07-19 07:09 UTC by jcmugabi

**What does this PR do**
- Pagination using infinite_scroll_pagination
- Share functionality
- Searching users by username (Still in progress)

**Tasks to be completed**
- Searching users by username
- Filter feature
- Welcome text
- Improve user details UI

2024-07-20 10:28 UTC, trishaagaba commented
This is good work

2024-07-20 10:31 UTC, trishaagaba reviewed
This is good work

2024-07-25 08:40 UTC, NabunyaLilian commented on lib/data/remote/api_urls.dart
remove comments

2024-07-25 09:09 UTC, NabunyaLilian requested changes
This is good work Mugabi, but resolve the changes requested

2024-07-25 09:09 UTC, NabunyaLilian commented on lib/presentation/screens/users_screen.dart
This method "_checkConnectivity()" in used in different files, you can create a utils folder, then create a helper functions page and add it in there. Then reuse it

2024-07-25 09:09 UTC, NabunyaLilian commented on lib/presentation/state/providers/internet_connection_provider.dart
Remove this widget in the provider. Providers shouldn't have widgets, just read the boolean isConnected from the widgets and create the card from there. You cn make the card a reusable widget, don't use methods , also use names that portray meaning.

2024-07-25 12:20 UTC, jcmugabi commented on lib/data/remote/api_urls.dart
Working on changes.

2024-07-26 06:50 UTC, NabunyaLilian approved these changes

2024-07-26 06:50 UTC, merged